FROM python:3.11-slim
ENV PYTHONUNBUFFERED 1
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app/
RUN chmod 777 /usr/src/app 
RUN chmod 777 /usr/src/app/entrypoint.sh
RUN apt-get update
RUN apt-get install -y build-essential
# RUN apt-get install -y python-dev
# RUN apt-get install -y python3-all-dev
RUN apt-get install -y uwsgi-plugin-python3
RUN apt-get install -y python3-dev 
RUN apt-get install -y gcc 
RUN apt-get install -y libevent-dev
RUN pip install --upgrade pip
RUN pip install markupsafe
RUN pip3 install matplotlib
RUN pip install Cython
RUN pip3 install transformers==4.39.3
RUN pip install uwsgi
RUN pip install --no-cache-dir -r requirements.txt
COPY ./uwsgi.ini /etc/uwsgi.ini
EXPOSE 5000
CMD ["./entrypoint.sh"]